version: '3'

# networks:
#   default:
#     external:
#       name:  profile_profile_net 

services:
  db:
    image: postgres
    container_name: translate_db
    command: -p 5435
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PERSISTENCE}
    networks:
      - default
    ports:
      - "5433:5435"

  django:
    build: ./api
    container_name: django_translate
    command: ash docker-entrypoint.sh
    volumes:
      - ./api:/api
    networks:
      - default
    environment:
      HOST_SERVER: ${HOST_SERVER}
    ports:
      - "9000:9000"
    depends_on:
      - db
